- ABLI: Abraham Lincoln Birthplace NHP
- ACAD: Acadia NP
- ADAM: Adams NHP
- AFBG: African Burial Ground NM
- AGFO: Agate Fossil Beds NM
- ALAG: Alagnak Wild River
- ALFL: Alibates Flint Quarries NM
- ALPO: Allegheny Portage Railroad NHS
- AMIS: Amistad NRA
- ANDE: Andersonville NHS
- ANJO: Andrew Johnson NHS
- ANIA: Aniakchak NM & PRES
- ANTI: Antietam NB
- APIS: Apostle Islands NL
- APCO: Appomattox Court House NHP
- ARCH: Arches NP
- ARPO: Arkansas Post NMEM
- ARHO: Arlington House The R.E. Lee MEM
- ASIS: Assateague Island NS
- AZRU: Aztec Ruins NM
- BADL: Badlands NP
- BAND: Bandelier NM
- BEPA: Belmont-Paul Women's Equality NM
- BEOL: Bent's Old Fort NHS
- BELA: Bering Land Bridge NPRES
- BIBE: Big Bend NP
- BICY: Big Cypress NPRES
- BIHO: Big Hole NB
- BISO: Big South Fork NRRA
- BITH: Big Thicket NPRES
- BICA: Bighorn Canyon NRA
- BICR: Birmingham Civil Rights NM
- BISC: Biscayne NP
- BLCA: Black Canyon of the Gunnison NP
- BLRV: Blackstone River Valley NHP
- BLRI: Blue Ridge PKWY
- BLUE: Bluestone NSR
- BOWA: Booker T. Washington NM
- BOAF: Boston African American NHS
- BOHA: Boston Harbor Islands NRA
- BOST: Boston NHP
- BRCR: Brices Cross Roads
- BRVB: Brown v. Board of Education NHS
- BRCA: Bryce Canyon NP
- BUIS: Buck Island Reef NM
- BUFF: Buffalo NR
- CABR: Cabrillo NM
- CANE: Camp Nelson NM
- CANA: Canaveral NS
- CARI: Cane River Creole NHP
- CACH: Canyon de Chelly NM
- CANY: Canyonlands NP
- CACO: Cape Cod NS
- CAHA: Cape Hatteras NS
- CAKR: Cape Krusenstern NM
- CALO: Cape Lookout NS
- CARE: Capitol Reef NP
- CAVO: Capulin Volcano NM
- CARL: Carl Sandburg Home NHS
- CAVE: Carlsbad Caverns NP
- CAWO: Carter G. Woodson Home NHS
- CAGR: Casa Grande Ruins NM
- CASA: Castillo de San Marcos NM
- CACL: Castle Clinton NM
- CAMO: Castle Mountains NM
- CATO: Catoctin Mountain Park
- CEBR: Cedar Breaks NM
- CECH: Cesar E. Chavez NM
- CHCU: Chaco Culture NHP
- CHAM: Chamizal NMEM
- CHIS: Channel Islands NP
- CHPI: Charles Pinckney NHS
- CHYO: Charles Young Buffalo Soldiers NM
- CHAT: Chattahoochee River NRA
- CHOH: Chesapeake & Ohio Canal NHP
- CHCH: Chickamauga & Chattanooga NMP
- CHIC: Chickasaw NRA
- CHIR: Chiricahua NM
- CHRI: Christiansted NHS
- CIRO: City of Rocks NRES
- CLBA: Clara Barton NHS
- COLO: Colonial NHP
- COLM: Colorado NM
- CONG: Congaree NP
- CORO: Coronado NMEM
- COWP: Cowpens NB
- CRLA: Crater Lake NP
- CRMO: Craters of the Moon NM & PRES
- CUGA: Cumberland Gap NHP
- CUIS: Cumberland Island NS
- CURE: Curecanti NRA
- CUVA: Cuyahoga Valley NP
- DAAV: Dayton Aviation Heritage NHP
- DESO: De Soto NMEM
- DEVA: Death Valley NP
- DEWA: Delaware Water Gap NRA
- DENA: Denali NP & PRES
- DEPO: Devils Postpile NM
- DETO: Devils Tower NM
- DINO: Dinosaur NM
- DRTO: Dry Tortugas NP
- DDEM: Dwight D. Eisenhower MEM
- EBLA: Ebey's Landing
- EDAL: Edgar Allan Poe NHS
- EFMO: Effigy Mounds NM
- EISE: Eisenhower NHS
- ELMA: El Malpais NM
- ELMO: El Morro NM
- ELRO: Eleanor Roosevelt NHS
- EUON: Eugene O'Neill NHS
- EVER: Everglades NP
- FEHA: Federal Hall NMEM
- FIIS: Fire Island NS
- FILA: First Ladies NHS
- FLNI: Flight 93 NMEM
- FLFO: Florissant Fossil Beds NM
- FOTH: Ford's Theatre NHS
- FOBO: Fort Bowie NHS
- FOCA: Fort Caroline NMEM
- FODA: Fort Davis NHS
- FODO: Fort Donelson NB
- FOFR: Fort Frederica NM
- FOLA: Fort Laramie NHS
- FOLS: Fort Larned NHS
- FOMA: Fort Matanzas NM
- FOMC: Fort McHenry NM & HS
- FOMR: Fort Monroe NM
- FONE: Fort Necessity NB
- FOPO: Fort Point NHS
- FOPU: Fort Pulaski NM
- FORA: Fort Raleigh NHS
- FOSC: Fort Scott NHS
- FOSM: Fort Smith NHS
- FOST: Fort Stanwix NM
- FOSU: Fort Sumter and Fort Moultrie NHP
- FOUN: Fort Union NM
- FOUS: Fort Union Trading Post NHS
- FOVA: Fort Vancouver NHS
- FOWA: Fort Washington Park
- FOBU: Fossil Butte NM
- FRDE: Franklin Delano Roosevelt MEM
- FRDO: Frederick Douglass NHS
- FRLA: Frederick Law Olmsted NHS
- FRSP: Fredericksburg & Spotsylvania NMP
- FRRI: Freedom Riders NM
- FRHI: Friendship Hill NHS
- GAAR: Gates of the Arctic NP & PRES
- JEFF: Gateway Arch NP
- GATE: Gateway NRA
- GARI: Gauley River NRA
- GEGR: General Grant NMEM
- GERO: George Rogers Clark NHP
- GEWA: George Washington Birthplace NM
- GWCA: George Washington Carver NM
- GWMP: George Washington MEM PKWY
- GETT: Gettysburg NMP
- GICL: Gila Cliff Dwellings NM
- GLBA: Glacier Bay NP & PRES
- GLAC: Glacier NP
- GLCA: Glen Canyon NRA
- GOGA: Golden Gate NRA
- GOSP: Golden Spike NHP
- GOIS: Governors Island NM
- GRCA: Grand Canyon NP
- GRPO: Grand Portage NM
- GRTE: Grand Teton NP
- GRKO: Grant-Kohrs Ranch NHS
- GRBA: Great Basin NP
- GRSA: Great Sand Dunes NP & PRES
- GRSM: Great Smoky Mountains NP
- GREE: Greenbelt Park
- GUMO: Guadalupe Mountains NP
- GUCO: Guilford Courthouse NMP
- GUIS: Gulf Islands NS
- HAFO: Hagerman Fossil Beds NM
- HALE: Haleakala NP
- HAGR: Hamilton Grange NMEM
- HAMP: Hampton NHS
- HAFE: Harpers Ferry NHP
- HATU: Harriet Tubman Underground Railroad NHP
- HSTR: Harry S Truman NHS
- HAVO: Hawaii Volcanoes NP
- HEHO: Herbert Hoover NHS
- HOFR: Home of Franklin D. Roosevelt NHS
- HOME: Homestead NHP
- HONO: Honouliuli NHS
- HOCU: Hopewell Culture NHP
- HOFU: Hopewell Furnace NHS
- HOBE: Horseshoe Bend NMP
- HOSP: Hot Springs NP
- HOVE: Hovenweep NM
- HUTR: Hubbell Trading Post NHS
- INDE: Independence NHP
- INDU: Indiana Dunes NP
- ISRO: Isle Royale NP
- JAGA: James A. Garfield NHS
- JELA: Jean Lafitte NHP & PRES
- JECA: Jewel Cave NM
- JICA: Jimmy Carter NHP
- JODR: John D. Rockefeller, Jr. MEM PKWY
- JODA: John Day Fossil Beds NM
- JOFK: John F. Kennedy Center For Pa
- JOFI: John F. Kennedy NHS
- JOMU: John Muir NHS
- JOFL: Johnstown Flood NMEM
- JOTR: Joshua Tree NP
- KALA: Kalaupapa NHP
- KAHO: Kaloko Honokohau NHP
- KAWW: Katahdin Woods and Waters NM
- KATM: Katmai NP & PRES
- KEFJ: Kenai Fjords NP
- KEMO: Kennesaw Mountain NBP
- KEWE: Keweenaw NHP
- KICA: Kings Canyon NP
- KIMO: Kings Mountain NMP
- KLGO: Klondike Gold Rush NHP Alaska
- KLSE: Klondike Gold Rush NHP Seattle
- KNRI: Knife River Indian Villages NHS
- KOVA: Kobuk Valley NP
- KOWA: Korean War Veterans Memorial
- LACH: Lake Chelan NRA
- LACL: Lake Clark NP & PRES
- LAKE: Lake Mead NRA
- LAMR: Lake Meredith NRA
- LARO: Lake Roosevelt NRA
- LAVO: Lassen Volcanic NP
- LABE: Lava Beds NM
- LYBA: LBJ Memorial Grove on the Potomac
- LEWI: Lewis & Clark NHP
- LIBO: Lincoln Boyhood NMEM
- LIHO: Lincoln Home NHS
- LINC: Lincoln Memorial
- LIBI: Little Bighorn Battlefield NM
- LIRI: Little River Canyon NPRES
- CHSC: Little Rock Central High School NHS
- LONG: Longfellow House Washington's HQ NHS
- LOWE: Lowell NHP
- LYJO: Lyndon B. Johnson NHP
- MAWA: Maggie L. Walker NHS
- MACA: Mammoth Cave NP
- MANA: Manassas NBP
- MAPR: Manhattan Project NHP
- MANZ: Manzanar NHS
- MABI: Marsh-Billings-Rockefeller NHP
- MLKM: Martin Luther King, Jr. Memorial
- MALU: Martin Luther King, Jr. NHP
- MAVA: Martin Van Buren NHS
- MABE: Mary McLeod Bethune Council House NHS
- MEMY: Medgar and Myrlie Evers Home NM
- MEVE: Mesa Verde NP
- MISP: Mill Springs Battlefield NM
- MIIN: Minidoka NHS
- MIMA: Minute Man NHP
- MIMI: Minuteman Missile NHS
- MISS: Mississippi NRRA
- MNRR: Missouri NRR
- MOJA: Mojave NPRES
- MONO: Monocacy NB
- MOCA: Montezuma Castle NM
- MOCR: Moores Creek NB
- MORR: Morristown NHP
- MORA: Mount Rainier NP
- MORU: Mount Rushmore NMEM
- MUWO: Muir Woods NM
- NATC: Natchez NHP
- NATR: Natchez Trace PKWY
- NCPC: National Capital Parks Central
- NACA: National Capital Parks Combined
- NCPE: National Capital Parks East
- NPSA: National Park of American Samoa
- NAVC: National Visitor Center
- NABR: Natural Bridges NM
- NAVA: Navajo NM
- NEBE: New Bedford Whaling NHP
- JAZZ: New Orleans Jazz NHP
- NERI: New River Gorge NP & PRES
- NEPE: Nez Perce NHP
- NICO: Nicodemus NHS
- NISI: Ninety Six NHS
- NIOB: Niobrara NSR
- NOAT: Noatak NPRES
- NOCA: North Cascades NP
- OBRI: Obed W&SR
- OCMU: Ocmulgee Mounds NHP
- OKCI: Oklahoma City NMEM
- OLYM: Olympic NP
- ORCA: Oregon Caves NM & PRES
- ORPI: Organ Pipe Cactus NM
- OZAR: Ozark NSR
- PAIS: Padre Island NS
- PAAL: Palo Alto Battlefield NHP
- PAGR: Paterson Great Falls NHP
- PERI: Pea Ridge NMP
- PERL: Pearl Harbor NMEM
- PECO: Pecos NHP
- PAAV: Pennsylvania Avenue NHS
- PEVI: Perry's Victory & Intl. Peace MEM
- PETE: Petersburg NB
- PEFO: Petrified Forest NP
- PETR: Petroglyph NM
- PIRO: Pictured Rocks NL
- PINN: Pinnacles NP
- PISP: Pipe Spring NM
- PIPE: Pipestone NM
- PISC: Piscataway Park
- PORE: Point Reyes NS
- POCH: Port Chicago Naval Magazine NMEM
- WICL: President W.J. Clinton Birthplace Home NHS
- PRPA: President's Park
- PRWI: Prince William Forest Park
- PULL: Pullman NM
- PUHO: Pu'uhonua o Honaunau NHP
- PUHE: Pu'ukohola Heiau NHS
- RABR: Rainbow Bridge NM
- REER: Reconstruction Era NHP
- REDW: Redwood NP
- RICH: Richmond NBP
- RIGR: Rio Grande W&SR
- RIRA: River Raisin NBP
- ROCR: Rock Creek Park
- ROMO: Rocky Mountain NP
- ROWI: Roger Williams NMEM
- RORI: Rosie The Riveter WWII Home Front NHP
- ROLA: Ross Lake NRA
- RUCA: Russell Cave NM
- SAHI: Sagamore Hill NHS
- SAGU: Saguaro NP
- SACR: Saint Croix Island IHS
- SACN: Saint Croix NSR
- SAPA: Saint Paul's Church NHS
- SAGA: Saint-Gaudens NHP
- SAMA: Salem Maritime NHS
- SAPU: Salinas Pueblo Missions NM
- SARI: Salt River Bay NHP & Ecological Pres
- SAAN: San Antonio Missions NHP
- SAFR: San Francisco Maritime NHP
- SAJH: San Juan Island NHP
- SAJU: San Juan NHS
- SAND: Sand Creek Massacre NHS
- SAMO: Santa Monica Mountains NRA
- SARA: Saratoga NHP
- SAIR: Saugus Iron Works NHS
- SCBL: Scotts Bluff NM
- SEQU: Sequoia NP
- SHEN: Shenandoah NP
- SHIL: Shiloh NMP
- SITK: Sitka NHP
- SLBE: Sleeping Bear Dunes NL
- SPAR: Springfield Armory NHS
- STLI: Statue of Liberty NM
- STGE: Ste. Genevieve NHP
- STEA: Steamtown NHS
- STRI: Stones River NB
- STON: Stonewall NM
- SUCR: Sunset Crater Volcano NM
- TAPR: Tallgrass Prairie NPRES
- THKO: Thaddeus Kosciuszko NMEM
- THRB: Theodore Roosevelt Birthplace NHS
- THRI: Theodore Roosevelt Inaugural NHS
- THIS: Theodore Roosevelt Island
- THRO: Theodore Roosevelt NP
- EDIS: Thomas Edison NHP
- JEFM: Thomas Jefferson MEM
- THST: Thomas Stone NHS
- TICA: Timpanogos Cave NM
- TIMU: Timucuan EHP
- TONT: Tonto NM
- TULE: Tule Lake NM
- TUSK: Tule Springs Fossil Beds NM
- TUMA: Tumacacori NHP
- TUPE: Tupelo NBS
- TUAI: Tuskegee Airmen NHS
- TUIN: Tuskegee Institute NHS
- TUZI: Tuzigoot NM
- ULSG: Ulysses S. Grant NHS
- UPDE: Upper Delaware S&RR
- VALL: Valles Caldera NPRES
- VAFO: Valley Forge NHP
- VAMA: Vanderbilt Mansion NHS
- VICK: Vicksburg NMP
- VIVE: Vietnam Veterans MEM
- VIIS: Virgin Islands NP
- VOYA: Voyageurs NP
- WACO: Waco Mammoth NM
- WACA: Walnut Canyon NM
- WAPA: War in the Pacific NHP
- WAMO: Washington Monument
- WABA: Washita Battlefield NHS
- WEFA: Weir Farm NHP
- WHIS: Whiskeytown NRA
- WHHO: White House
- WHSA: White Sands NP
- WHMI: Whitman Mission NHS
- WIHO: William Howard Taft NHS
- WICR: Wilson's Creek NB
- WICA: Wind Cave NP
- WOTR: Wolf Trap NP for the Performing Arts
- WORI: Women's Rights NHP
- WWIM: World War I Memorial
- WWII: World War II Memorial
- WRST: Wrangell-St. Elias NP & PRES
- WRBR: Wright Brothers NMEM
- WUPA: Wupatki NM
- YELL: Yellowstone NP
- YOSE: Yosemite NP
- YUCH: Yukon-Charley Rivers NPRES
- ZION: Zion NP
