- BIBE: Big Bend NP
- BITH: Big Thicket NPRES
- BICR: Birmingham Civil Rights NM
- BLRV: Blackstone River Valley NHP
- BLRI: Blue Ridge PKWY
- BOWA: Booker T. Washington NM
- BOAF: Boston African American NHS
- BOHA: Boston Harbor Islands NRA
- BUIS: Buck Island Reef NM
- BUFF: Buffalo NR
