EHP: Ecological and Historic Preserve
MEM: Memorial
NB: National Battlefield
NBS: National Battlefield Site
NHP: National Historical Park
NHS: National Historic Site
NHT: National Historic Trail
NL: National Lakeshore
NM: National Monument
NMEM: National Memorial
NMP: National Military Park
NP: National Park
NPRES: National Preserve
NR: National River
NRA : National Recreation Area
NRRA: National River and Recreation Area
NS : National Seashore
NSR: National Scenic River
NST: National Scenic Trail
PK: Park
PKWY: Parkway
"W&SR": Wild and Scenic River