# Main configuration file for national-parks project

refresh_source:
  # Flag for refreshing all parks or a sample thereof
  refresh_all_parks: False
  park_sets:
    all: config/source_capta/all_parks.yaml
    sample: config/source_capta/sample_parks.yaml
  # Inclusive range of years for which to gather capta
  date_range:
    min: 1979
    max: 2021
  # URLs and paths associated with capta scraped from the National Parks Service
  nps:
    monthly_visitors:
      base_url: https://irma.nps.gov/STATS/SSRSReports/Park%20Specific%20Reports/Recreation%20Visitors%20By%20Month%20(1979%20-%20Last%20Calendar%20Year)?Park={park}
      output_path: capta/source/nps_monthly_visitors.csv
    visitor_use:
      base_url: https://irma.nps.gov/STATS/SSRSReports/Park%20Specific%20Reports/Summary%20of%20Visitor%20Use%20By%20Month%20and%20Year%20(1979%20-%20Last%20Calendar%20Year)?Park={park}
      output_path: capta/source/nps_visitor_use.csv

process:
  # Source capta used to "prime the pump" for the processing steps outlined
  # below
  inputs:
    - name: nps_monthly_visitors
      path: capta/source/nps_monthly_visitors.csv
  # Each step takes the input and executes the indicated sequence of
  # transformations, caching the processed result so that it can be used as the
  # input for later steps. If an output_path is indicated, the processed result
  # is also written there.
  # NB: each step must have at least one transformation - if no "real"
  # transformations need to be executed then an "identity" transformation should
  # still be executed
  steps:
    - name: melt_monthly_visitors
      input: nps_monthly_visitors  # TODO (WW): figure out how to have multiple inputs for a step
      transformations:
        - name: columns_to_lowercase
        - name: melt
          params:
            id_vars:
              - park_name
              - park_type
              - year
            var_name: month
            value_name: visitors
        - name: create_dt_pk
          params:
            year_col: year
            month_col: month
      output: tall_monthly_visitors
    - name: pivot_visitors_by_park
      input: tall_monthly_visitors
      transformations:
        - name: pivot
          params:
            index: dt_pk
            columns: park_name
            values: visitors
      output: monthly_visitors_by_park
      output_path: capta/processed/monthly_visitors_by_park.csv
    - name: pivot_visitors_by_park_type
      input: tall_monthly_visitors
      transformations:
        - name: sum_by
          params:
            by:
              - park_type
              - dt_pk
            summands:
              - visitors
        - name: pivot
          params:
            index: dt_pk
            columns: park_type
            values: visitors
      output: monthly_visitors_by_park_type
      output_path: capta/processed/monthly_visitors_by_park_type.csv
