# Main configuration file for national-parks project. Each top-level entry
# matches a DVC stage.

refresh_source_capta:  # TODO (WW): consider offloading these as well, depending on how this step evolves
  # Flag for refreshing all parks or a sample thereof
  refresh_all_parks: False
  # Park names corresponding to the full captaset and to a sample useful for
  # development and testing
  park_sets:
    all: config/refresh_source_capta/all_parks.yaml
    sample: config/refresh_source_capta/sample_parks.yaml
  # Inclusive range of years for which to gather capta
  date_range:
    min: 1979
    max: 2021
  # URLs and paths associated with capta scraped from the National Parks Service
  nps:
    monthly_visitors:
      base_url: https://irma.nps.gov/STATS/SSRSReports/Park%20Specific%20Reports/Recreation%20Visitors%20By%20Month%20(1979%20-%20Last%20Calendar%20Year)?Park={park}
      output_path: capta/source/nps_monthly_visitors.csv
    visitor_use:
      base_url: https://irma.nps.gov/STATS/SSRSReports/Park%20Specific%20Reports/Summary%20of%20Visitor%20Use%20By%20Month%20and%20Year%20(1979%20-%20Last%20Calendar%20Year)?Park={park}
      output_path: capta/source/nps_visitor_use.csv

process_capta:
  inputs: config/process_capta/inputs.yaml
  steps: config/process_capta/steps.yaml

train_models:
  inputs: config/train_models/inputs.yaml
  recipes: config/train_models/recipes.yaml